### ISSUE TITLE
version IRI in OLS does not resolve

### ISSUE THREAD

**Issue by marieALaporte** [CompositionalDietaryNutritionOntology/cdno#98]
the version IRI link on the OLS (Version IRI: [ http://purl.obolibrary.org/obo/cdno/releases/2022-06-23/cdno.owl](http://purl.obolibrary.org/obo/cdno/releases/2022-06-23/cdno.owl)) does not resolved as the GitHub release tag should have a v before the date (e.g. v2022-06-23).

**Comment by LilyAndres** [comment]
Thanks @marieALaporte. @ddooley I followed FoodOn and ENVO naming convention... what do you think?

**Comment by marieALaporte** [comment]
The OLS IRI version link doesn't resolve for FoodOn either apparently @ddooley 
It works for ENVO as the release tag is following the vYYYY-MM-DD format. 

If you look at the [README-editor.md](https://github.com/Southern-Cross-Plant-Science/cdno/blob/master/src/ontology/README-editors.md#release-manager-notes) file, the naming convention for release tags is described

**Comment by ddooley** [comment]
I've noticed that the version IRI doesn't necessarily lead to a file by that name for a number of OBO ontologies. I'll ask if there is any policy around that in next OBO operations meeting.

**Comment by ddooley** [comment]
So I see official OBO policy is that version iri link should lead to a release.  I'll have to make that so for subsequent FoodOn releases.

**Comment by LilyAndres** [comment]
@ddooley thanks. @marieALaporte thanks, I have edited the release title but it might take some time for OLS to update? I will check if this gets sorted.

**Comment by LilyAndres** [comment]
@marieALaporte apologies, just took some time to prepare the release. 
I just made a new release with the changes you suggested, thanks a lot. I hope it's ok now, please let me know if you are still having an issue.

**Comment by LilyAndres** [comment]
Hi @kaiiam , I changed the version name but I have the feeling that this is incorrect and should be 3.3, 3.4, 4.0, etc. Instead of the vYYYY-MM-DD format, as it is right now. Hopefully the issue makes sense, if not please let me know. 

I also can see that OLS is not picking up the latest release of CDNO, I'm not sure if it's related to the same versioning name. Please let me know what you think. Thanks a lot.

**Comment by ddooley** [comment]
OLS is stalled on refreshing ontologies recently apparently, while they resolve some technical issues.

**Comment by kaiiam** [comment]
> 3.3, 3.4, 4.0, etc. Instead of the vYYYY-MM-DD format, as it is right now.

I think either is probably fine. Lets just pick something and go with it. We did dates before but if you want to change to numbered versions that's up to you @LilyAndres.

**Comment by LilyAndres** [comment]
Thanks @kaiiam, we were ok with the numbering versions 3.3, 4.0, etc. but as @marieALaporte mentioned it should be different so we changed it two versions ago...

> The name tag needs to be vYYYY-MM-DD. You cannot just change the name. In the release file, the version are based on dates:
<owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/cdno/releases/2022-06-23/cdno.owl"/>
The URL for the PURL redirection is build using that information. See [here](https://github.com/OBOFoundry/purl.obolibrary.org/blob/00c8f9bee25bd4a83b54a5ebeb70ef78c6879fca/config/cdno.yml#L17)
I think you can update the GitHub release information without needing a new release, although I am not 100% sure about that. I remember we had to go through a similar process for TO at one time.

Just wondering if this is actually ok, some users are a bit confused since que changed the numbering version, that's why...

**Comment by ddooley** [comment]
My two bits - the issue with ontologies and numbering is its not always clear what constitutes a jump in x.y.z style https://semver.org/ major/minor/patch whereas with dates one immediately understands how recent it is, and avoids the x.y.z issue.

**Comment by kaiiam** [comment]
All of our previous releases use the `vYYYY-MM-DD` format and I don't see anything wrong with that. I'd advise sticking with that to be consistent.
